# Generated by Django 2.1.1 on 2018-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180924_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='feed.Category'),
        ),
    ]
