# Generated by Django 2.1.1 on 2018-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20180924_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date_time', models.DateTimeField()),
                ('category', models.ManyToManyField(to='feed.Category')),
            ],
        ),
    ]
