# Generated by Django 2.1.1 on 2018-09-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Category'),
        ),
    ]
