# Generated by Django 2.1.1 on 2018-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_answer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='locoLink',
            field=models.URLField(default=1),
        ),
    ]
